config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/test", to: "pages#test"
  get "/analytics", to: "pages#analytics"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User"
  has_many :event_attendances
  has_many :attendees, through: :event_attendances, source: :user
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :caption, length: { maximum: 200 }

  has_many :likes
  has_many :liking_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :username, presence: true
  validates :username, uniqueness: true

  has_many :posts
  has_many :event_attendances
  has_many :events, through: :event_attendances
  has_many :follower_relationships, class_name: "Follow", foreign_key: "source_id"
  has_many :follower_relationships, class_name: "Follow", foreign_key: "target_id"

  # Interests
  has_many :user_interests
  has_many :interests, through: :user_interests

  # events
  has_many :hosted_events, class_name: "Event", foreign_key: "host_id"
  has_many :event_attendances
  has_many :attended_events, through: :event_attendances, source: :event

  # Posts
  has_many :posts

  # Likes
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest

  validates :rating, numericality: { in: 1..10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Is this the best way to add usrname?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def analytics

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="#">NEW WAVE SOCIAL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Discover</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Events</a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu">
              <li>
                <% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete}  %>
                <% else %>
                <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
                <% end %>
              </li>
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialAppJan25</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <%= render 'layouts/sidebar' %>
        <%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/analytics.html.erb
<h1> Analytics </h1>

app/views/pages/home.html.erb
<div class="banner">
  <img src="https://cdn.pixabay.com/photo/2023/10/23/17/03/audi-8336484_1280.jpg" alt="Banner Image">
  <div class="banner-content">
    <h1>Welcome to NEW WAVE</h1>
    <p>Community building in the creator's economy</p>
    <div>
      <a href="#" class="btn btn-primary btn-lg">Explore</a>
      <a href="#" class="btn btn-secondary btn-lg">New Post</a>
    </div>
  </div>
</div>

app/views/pages/test.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testing BS</title>
    <link rel="stylesheet" href="css/styles.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <nav id="sidebar" class="col-12 col-md-3 col-lg-2 bg-dark text-white p-3">
                <div class="top-section-sidebar">
                      <div class="text-center mb-3">
                        <%= link_to root_path do %>
                          <%= image_tag "fs-icon-1.png", alt: "Logo", class: "img-fluid sidebar-logo" %>
                        <% end %>
                     </div>
                    <hr>
                    <ul class="nav flex-column">
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-house"></i> Home
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-box-open"></i> Crates
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-earth-europe"></i> Events
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-calendar-days"></i> Events Schedule
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-chart-line"></i> Analytics
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(test_path) %>">
                            <%= link_to test_path, class: "nav-link" do %>
                              <i class="fas fa-user me-2"></i> Profile
                            <% end %>
                        </li>
                        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                            <%= link_to root_path, class: "nav-link" do %>
                              <i class="fa-solid fa-gear"></i> Settings
                            <% end %>
                        </li>
                    </ul>
                </div>
                <div class="bottom-section-sidebar">
                  <hr>
                  <div class="dropdown">
                    <a href="#" class="d-flex align-items-center text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                      <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                      <strong>oskvitae</strong>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                      <li><a class="dropdown-item" href="#">New project...</a></li>
                      <li><a class="dropdown-item" href="#">Settings</a></li>
                      <li><a class="dropdown-item" href="#">Profile</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                  </div>
                </div>
            </nav>


            <!-- Main Content -->
            <main id="main-content" class="col-12 col-md-9 col-lg-10 p-4">
                <h1>Bootstrap Sidebar Testing</h1>
                <p>Sticky sidebar for the bwoi.</p>
                <div class="tall-container coral"></div>
                <div class="tall-container blue"></div>
                <div class="tall-container coral"></div>
            </main>
        </div>
    </div>
</body>


</html>